# Generated by Django 5.1.6 on 2025-05-13 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('SupplierCode', models.CharField(help_text='Unique identifier for the supplier (manually given).', max_length=50, primary_key=True, serialize=False)),
                ('SupplierName', models.CharField(max_length=255)),
                ('Category', models.CharField(choices=[('Ingredient', 'Ingredient'), ('Packaging', 'Packaging'), ('Both', 'Both')], max_length=10)),
                ('SocialMedia', models.CharField(blank=True, max_length=255, null=True)),
                ('EmailAddress', models.CharField(blank=True, max_length=320, null=True)),
                ('ContactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('change_status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('PointPerson', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PackagingRawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('PackagingBatchCode', models.CharField(blank=True, max_length=50, unique=True)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('ContainerSize', models.CharField(default='N/A', max_length=50)),
                ('DateDelivered', models.DateField()),
                ('QuantityBought', models.IntegerField(default=0)),
                ('QuantityLeft', models.IntegerField(default=0)),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], default='GGB', max_length=10)),
                ('Status', models.CharField(choices=[('Low Inventory', 'Low Inventory'), ('OK', 'OK')], default='OK', max_length=50)),
                ('Cost', models.FloatField(default=0)),
                ('change_status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('SupplierCode', models.ForeignKey(db_column='SupplierCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientsRawMaterials',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('RawMaterialBatchCode', models.CharField(blank=True, max_length=50, unique=True)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('DateDelivered', models.DateField()),
                ('QuantityBought', models.FloatField(default=0)),
                ('QuantityLeft', models.FloatField(default=0)),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], default='GGB', max_length=10)),
                ('ExpirationDate', models.DateField()),
                ('Status', models.CharField(default='Good', max_length=50)),
                ('Cost', models.FloatField(default=0)),
                ('change_status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('SupplierCode', models.ForeignKey(db_column='SupplierCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='UsedIngredient',
            fields=[
                ('UsedIngredientBatchCode', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('QuantityUsed', models.FloatField()),
                ('DateUsed', models.DateField()),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], max_length=10)),
                ('change_status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('IngredientRawMaterialBatchCode', models.ForeignKey(db_column='IngredientRawMaterialBatchCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.ingredientsrawmaterials')),
            ],
        ),
        migrations.CreateModel(
            name='UsedPackaging',
            fields=[
                ('USEDPackagingBatchCode', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('RawMaterialName', models.CharField(max_length=255)),
                ('QuantityUsed', models.IntegerField()),
                ('DateUsed', models.DateField()),
                ('UseCategory', models.CharField(choices=[('WBC', 'WBC'), ('GGB', 'GGB'), ('Both', 'Both')], max_length=10)),
                ('change_status', models.CharField(choices=[('active', 'Active'), ('deleted', 'Deleted')], default='active', max_length=10)),
                ('PackagingRawMaterialBatchCode', models.ForeignKey(db_column='PackagingRawMaterialBatchCode', on_delete=django.db.models.deletion.CASCADE, to='IMAPS_app.packagingrawmaterials')),
            ],
        ),
    ]
