# Generated by Django 5.0.4 on 2025-05-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("IMAPS_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="change_status",
            field=models.CharField(
                choices=[("active", "Active"), ("deleted", "Deleted")],
                default="active",
                max_length=50,
            ),
        ),
    ]
